package com.dewmark.smartcampuscommunity.pojo.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * 用户帖子点赞关系表实体类
 * 
 * @author Generated By System
 * @date 2024-01-15
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@TableName("user_post_likes")
public class UserPostLike {
    
    /**
     * 自增主键ID
     */
    private Long id;
    
    /**
     * 用户ID
     */
    private Long userId;
    
    /**
     * 帖子ID
     */
    private Long postId;
    
    /**
     * 点赞状态：1-点赞，0-取消点赞
     */
    private Integer likeStatus;
    
    /**
     * 创建时间
     */
    private LocalDateTime createdAt;
    
    /**
     * 更新时间
     */
    private LocalDateTime updatedAt;
}